var myPokedex={
  Garth:{
    name: "Garth",
    species: "Golem",
    type: "Rock/Ground",
    arrival: ["Caught","08.01.16"],
    "nursery role": "Sentry",
    moves:["Mud Shot","Ancient Power"],
    IV: 24,
    notes:"",
  },
  Kingsmouth:{
    name: "Kingsmouth",
    species: "Tentacruel",
    type: "Water/Poison",
    arrival: ["Hatched","08.17.16"],
    "nursery role": "none",
    moves:["Poison Jab","Hydro Pump"],
    IV: 43,
    notes:"",
  },
  Legate:{
    name: "Legate",
    species: "Ninetails",
    type: "Fire",
    arrival: ["Caught","08.10.16"],
    "nursery role": "Beta",
    moves:["Feint Attack","Fire Blast"],
    IV: 25,
    notes:"",
  },
  Mani:{
    name: "Mani",
    species: "Charmander",
    type: "Fire",
    arrival: ["Caught","08.21.16"],
    "nursery role": "none",
    moves:["Ember","Fire Burst"],
    IV: 24,
    notes:"",
  },
  Onarine:{
    name: "Onarine",
    species: "Flareon",
    type: "Fire",
    arrival: ["Hatched","08.05.16"],
    "nursery role": "none",
    moves:["Ember","Fire Burst"],
    IV: 36,
    notes:"Formerly known as 'Ember'",
  },
  Reeby:{
    name: "Reeby",
    species: "Pidgeot",
    type: "Flying",
    arrival: ["Caught","07.23.16"],
    "nursery role": "Beta",
    moves:["Steel Wing","Aerial Ace"],
    IV: 34,
    notes:"",
  },
  Ronin:{
    name: "Ronin",
    species: "Jolteon",
    type: "Electric",
    arrival: ["Hatched","07.28.16"],
    "nursery role": "Alpha",
    moves:["Thunder Shock","Thunder"],
    IV: 37,
    notes:"",
  },
  Wakizashi:{
    name: "Wakizashi",
    species: "Raichu",
    type: "Electric",
    arrival: ["Hatched","08.16.16"],
    "nursery role": "none",
    moves:["Thunder Shock","Thunder"],
    IV: 39,
    notes:"",
  }
}

module.exports=myPokedex;
