var myPokedex={
  Freya:{
    name: "Freya",
    species: "Primeape",
    type: "Fighting",
    arrival:["Caught*","08.03.16"],
    moves:["Low Kick","Low Sweep"],
    IV:41,
    notes:"True to her type, Freya is one of few of our residents who truly loves the gym."
  },
  Garth:{
    name: "Garth",
    species: "Golem",
    type: "Rock/Ground",
    arrival: ["Caught*","08.01.16"],
    moves:["Mud Slap","Ancient Power"],
    IV: 43,
    notes:"Garth, unbidden, installed himself as nursery sentry upon his evolution and takes little notice of other residents as he patrols.",
  },
  Kettle:{
    name: "Kettle",
    species: "Rhydon",
    type: "Ground/Rock",
    arrival:["Caught*","08.18.16"],
    moves:["Rock Smash", "Stone Edge"],
    IV:45,
    notes:"Truly a gentle giant, though he'll scratch against anything hard enough, even if he destroys it in the process. Currently our only pokemon rated as a 45!",
  },
  Kingsmouth:{
    name: "Kingsmouth",
    species: "Tentacruel",
    type: "Water/Poison",
    arrival: ["Hatched","08.17.16"],
    moves:["Poison Jab","Hydro Pump"],
    IV: 43,
    notes:"",
  },
  Legate:{
    name: "Legate",
    species: "Ninetails",
    type: "Fire",
    arrival: ["Caught","08.10.16"],
    moves:["Feint Attack","Fire Blast"],
    IV: 25,
    notes:"",
  },
  Mani:{
    name: "Mani",
    species: "Charmander",
    type: "Fire",
    arrival: ["Caught","08.21.16"],
    moves:["Ember","Fire Burst"],
    IV: 24,
    notes:"",
  },
  Onarine:{
    name: "Onarine",
    species: "Flareon",
    type: "Fire",
    arrival: ["Hatched","08.05.16"],
    moves:["Ember","Fire Burst"],
    IV: 36,
    notes:"Formerly known as 'Ember'",
  },
  Reeby:{
    name: "Reeby",
    species: "Pidgeot",
    type: "Flying",
    arrival: ["Caught","07.23.16"],
    moves:["Steel Wing","Aerial Ace"],
    IV: 34,
    notes:"",
  },
  Ronin:{
    name: "Ronin",
    species: "Jolteon",
    type: "Electric",
    arrival: ["Hatched","07.28.16"],
    moves:["Thunder Shock","Thunder"],
    IV: 37,
    notes:"",
  },
  Wakizashi:{
    name: "Wakizashi",
    species: "Raichu",
    type: "Electric",
    arrival: ["Hatched","08.16.16"],
    moves:["Thunder Shock","Thunder"],
    IV: 39,
    notes:"",
  }
}

module.exports=myPokedex;
